variables:
- name: Build.Clean
  value: true

jobs:
- job: build_resume
  displayName: Build Resume
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell:
      npm install
    displayName: Restore npm modules

  - powershell:
      npm install -g @angular/cli@8.3.6
    displayName: Install angular cli tools

  - powershell:
      ng build --prod
    displayName: Build angular application